box_colors = ["#FEFEFE", "#C0C0C0", "#404040", "#000000"]  # white, light grey, grey, black
palette = []
currTile = []
tileSet= []
tileMap=[]
currTileIndex=0
grid_frame=None
selectedColor = 0  # Default selected color
editingTile=True
tileMapReal=[]
tileMapRealGraphic=[]
app=None